// Generated by gencpp from file robotis_controller_msgs/SensorYPR.msg
// DO NOT EDIT!


#ifndef ROBOTIS_CONTROLLER_MSGS_MESSAGE_SENSORYPR_H
#define ROBOTIS_CONTROLLER_MSGS_MESSAGE_SENSORYPR_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robotis_controller_msgs
{
template <class ContainerAllocator>
struct SensorYPR_
{
  typedef SensorYPR_<ContainerAllocator> Type;

  SensorYPR_()
    : pitch(0.0)
    , roll(0.0)
    , yaw(0.0)  {
    }
  SensorYPR_(const ContainerAllocator& _alloc)
    : pitch(0.0)
    , roll(0.0)
    , yaw(0.0)  {
  (void)_alloc;
    }



   typedef double _pitch_type;
  _pitch_type pitch;

   typedef double _roll_type;
  _roll_type roll;

   typedef double _yaw_type;
  _yaw_type yaw;





  typedef boost::shared_ptr< ::robotis_controller_msgs::SensorYPR_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robotis_controller_msgs::SensorYPR_<ContainerAllocator> const> ConstPtr;

}; // struct SensorYPR_

typedef ::robotis_controller_msgs::SensorYPR_<std::allocator<void> > SensorYPR;

typedef boost::shared_ptr< ::robotis_controller_msgs::SensorYPR > SensorYPRPtr;
typedef boost::shared_ptr< ::robotis_controller_msgs::SensorYPR const> SensorYPRConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robotis_controller_msgs::SensorYPR_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robotis_controller_msgs::SensorYPR_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace robotis_controller_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'robotis_controller_msgs': ['/home/robotis/catkin_ws/src/ROBOTIS-Framework-msgs/robotis_controller_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::robotis_controller_msgs::SensorYPR_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robotis_controller_msgs::SensorYPR_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robotis_controller_msgs::SensorYPR_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robotis_controller_msgs::SensorYPR_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robotis_controller_msgs::SensorYPR_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robotis_controller_msgs::SensorYPR_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robotis_controller_msgs::SensorYPR_<ContainerAllocator> >
{
  static const char* value()
  {
    return "da3691d617cf6ed55be8bea5c4931fd8";
  }

  static const char* value(const ::robotis_controller_msgs::SensorYPR_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xda3691d617cf6ed5ULL;
  static const uint64_t static_value2 = 0x5be8bea5c4931fd8ULL;
};

template<class ContainerAllocator>
struct DataType< ::robotis_controller_msgs::SensorYPR_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robotis_controller_msgs/SensorYPR";
  }

  static const char* value(const ::robotis_controller_msgs::SensorYPR_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robotis_controller_msgs::SensorYPR_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 pitch\n\
float64 roll\n\
float64 yaw\n\
";
  }

  static const char* value(const ::robotis_controller_msgs::SensorYPR_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robotis_controller_msgs::SensorYPR_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pitch);
      stream.next(m.roll);
      stream.next(m.yaw);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SensorYPR_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robotis_controller_msgs::SensorYPR_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robotis_controller_msgs::SensorYPR_<ContainerAllocator>& v)
  {
    s << indent << "pitch: ";
    Printer<double>::stream(s, indent + "  ", v.pitch);
    s << indent << "roll: ";
    Printer<double>::stream(s, indent + "  ", v.roll);
    s << indent << "yaw: ";
    Printer<double>::stream(s, indent + "  ", v.yaw);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOTIS_CONTROLLER_MSGS_MESSAGE_SENSORYPR_H
