gaussian_blur_size: 7
gaussian_blur_sigma: 2.64
canny_edge_th: 87
hough_accum_resolution: 3.29
min_circle_dist: 131.1
hough_accum_th: 172.9
min_radius: 14
max_radius: 593
filter_h_min: 311
filter_h_max: 36
filter_s_min: 139
filter_s_max: 247
filter_v_min: 1
filter_v_max: 255
use_second_filter: false
filter2_h_min: 41
filter2_h_max: 345
filter2_s_min: 32
filter2_s_max: 190
filter2_v_min: 48
filter2_v_max: 252
ellipse_size: 3
filter_debug: false